name: library_fe
description: Todo frontend
version: 0.0.1

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  angular: ^5.0.0
  angular_forms: ^2.0.0
  angular_router: ^2.0.0-alpha+19
  http: ^0.12.0+2
  stream_transform: ^0.0.6

dev_dependencies:
  angular_test: ^2.0.0
  build_runner: ^1.7.2
  build_test: ^0.10.0
  build_web_compilers: ^2.7.1
  mockito: ^3.0.0-beta+1
  pageloader: ^3.0.0
  test: ^1.0.0
